# HttpServer settings
httpServer:
  enabled: true
  publicAddress: "" #主机IP地址
  port: 8123 #需要为主机开放一个没有被占用的TCP端口
  servePath: "musicpacks"
  tempDirectory: "temp_packs"
  maxDownloadSizeBytes: 104857600
  musicRoomInactiveCleanupDelaySeconds: 600

# Base Resource Pack (Managed by EogdMusicPlayer) - OPTIONAL
# 如果配置了此项并且文件存在，音乐将被注入到此基础包的副本中。
# 如果未配置或文件不存在，插件将生成独立的音乐资源包。
# 你需要把基础资源包放进插件文件夹(服务器根目录/plugins/EogdMusicPlayer/) 中
baseResourcePack:
  # 设置为 true 以尝试使用基础包合并逻辑。如果 fileName 无效或文件不存在，将回退到独立包模式。
  enableMerging: false
  fileName: "base_pack.zip"     # 基础资源包的文件名。仅当 enableMerging 为 true 时使用。
  promptMessage: "§6加载音乐资源包..." # 发送包含音乐的资源包时的提示信息。
  # originalPackPromptMessage 仅在 enableMerging = true 且成功加载基础包后，恢复原始基础包时使用。
  originalPackPromptMessage: "§6恢复服务器默认资源包..."

# Fallback/Independent Resource pack settings (used if baseResourcePack.enableMerging is false or base_pack.zip is not found)
# 也用于在合并模式下，如果基础包没有 pack.mcmeta 时，提供默认的 pack_format 和 description。
resourcePack:
  packFormat: 32 # For Minecraft 1.20.5 - 1.20.6
  description: "§b音乐播放器资源包" # 用于独立包，或作为合并模式的备用描述

# Preset songs
presetSongs:
  song1:
    name: "§a天真的橡皮DJ"
    url: "https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1746857907489/M500001tcBK93IIRzk.ogg"
    item: "MUSIC_DISC_13"
    lore:
      - "§7这是一首示例歌曲"
      - "§9点击播放！"
  song2:
    name: "§b天地上乗有頂天"
    url: "https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1746857909117/M500002B21S90lruet.ogg"
    item: "MUSIC_DISC_CAT"
    lore:
      - "§6fumofumo"
      - "§e点击播放!"

# GUI Settings
gui:
  title: "§9音乐播放器"
  nextPageItem: "ARROW"
  nextPageName: "§a下一页 ->"
  prevPageItem: "ARROW"
  prevPageName: "§c<- 上一页"
  noPresets: "§c没有可用的预设歌曲。"

# Messages (use § or & for colors)
messages:
  general:
    playerOnly: "§c此命令只能由玩家执行。"
    noPermission: "§c你没有权限执行此命令。"
    httpDisabled: "§cHTTP服务器未启用，此功能不可用。"
    invalidUrl: "§c提供的URL无效或为空。"
    basePackMissing: "§e警告: 未找到配置的基础资源包，将使用独立音乐包模式。" # Changed message
    basePackReapplyFailed: "§c恢复服务器默认资源包失败。请联系管理员。"
  bf:
    usage: |-
      §6EogdMusicPlayer 命令:
      §e/bf play <歌曲名称/编号>§7 - 播放预设歌曲
      §e/bf playurl <URL>§7 - 播放指定URL的音乐 (仅自己听)
      §e/bf stop§7 - 停止当前为你播放的音乐
      §e/bf gui§7 - 打开音乐播放GUI
      §e/bf createroom <URL> <描述>§7 - 创建一个音乐室
      §e/bf join <发起者名称>§7 - 加入一个音乐室
      §e/bf start§7 - 为你的音乐室开始播放音乐 (仅房主)
      §e/bf roomplay <新URL>§7 - 更新你音乐室的音乐URL (仅房主)
      §e/bf disbandroom§7 - 解散你创建的音乐室 (仅房主)
      §e/bf reload§7 - 重载插件配置
      §e/bf info§7 - 查看插件信息
    unknownCommand: "§c未知子命令。使用 /bf 获取帮助。"
    play:
      usage: "§6用法: /bf play <歌曲名称或编号>"
      notFound: "§c未找到名为或编号为 '§e<song>§c' 的预设歌曲。"
    playurl:
      usage: "§6用法: /bf playurl <URL>"
      preparing: "§e正在准备音乐资源包..."
      packCreationFailed: "§c创建资源包失败。"
      error: "§c播放音乐时发生错误。"
    stop:
      stoppedForSelf: "§a已为你停止播放音乐。"
      roomStopped: "§a已停止音乐室 '§e<room_description>§a' 的音乐播放。"
      notPlaying: "§e当前没有为你播放音乐。"
    createroom:
      usage: "§6用法: /bf createroom <URL> <描述>"
      noDescription: "§c请输入音乐室的描述。"
      alreadyCreated: "§e你已经创建了一个音乐室: §f<room_description>§e。请先解散它。"
      successWithStartHint: "§a音乐室 '§e<description>§a' 已创建！URL: §f<url>§a。使用 §e/bf start §a开始播放。"
      broadcast: "§b<creator_name> §a创建了音乐室 描述:§f <description> §a输入§e /bf join <creator_name> §a来加入吧！"
    join:
      usage: "§6用法: /bf join <发起者名称>"
      roomNotFound: "§c未找到由 '§e<creator>§c' 发起的音乐室。"
      alreadyCreator: "§e你已经是这个音乐室的发起者了！"
      alreadyMember: "§e你已经是音乐室 '§f<room_description>§e' 的成员了。"
      leftOtherRoom: "§8你已离开之前的音乐室: §7<other_room_description>"
      successNoAutoPlay: "§a成功加入音乐室: §f<room_description>§a！等待房主开始播放音乐。"
      internalRoomNotFound: "§c内部错误：找不到指定的音乐室ID。"
    reload:
      success: "§aEogdMusicPlayer 配置已重载。"
    room:
      start:
        notRoomCreator: "§c你不是任何音乐室的创建者。"
        noMusicUrl: "§c你的音乐室 '§e<room_description>§c' 当前没有设置音乐URL。请使用 §e/bf roomplay <URL> §c设置。"
        startingMusic: "§a正在为音乐室 '§e<room_description>§a' 的所有成员准备并发送音乐资源包..."
        memberStartNotification: "§6房主已开始播放音乐！请接受资源包。"
      play:
        usage: "§6用法: /bf roomplay <新音乐URL>"
        notRoomCreator: "§c你不是任何音乐室的创建者。"
        urlSet: "§a音乐室 '§e<room_description>§a' 的音乐URL已更新为: §f<url>§a。使用 §e/bf start §a开始播放。"
        urlSame: "§e音乐室 '§f<room_description>§e' 的URL未改变。使用 §b/bf start §e重新播放。"
    disbandroom:
      notCreatorOrNoRoom: "§c你没有创建音乐室，或无法解散它。"
      success: "§a音乐室 '§e<room_description>§a' 已成功解散。"
      notifyMemberRoomDisbanded: "§e你所在的音乐室 '§f<room_description>§e' 已被创建者解散。"
  playurl:
    usage: "§6用法: /playurl <URL>"
    preparing: "§e正在准备音乐资源包..."
    packCreationFailed: "§c创建资源包失败。"
    error: "§c播放音乐时发生错误。"
  resourcePack:
    status:
      accepted: "§a资源包已接受！"
      declined: "§c资源包被拒绝。无法播放音乐。"
      failed: "§6资源包下载失败。请检查你的网络或服务器控制台日志。"
      successfully_loaded: "§9资源包加载成功！"
  musicRoomClosedMessage: "§c音乐室 '§e<description>§c' 因长时间不活动或发起者离开已关闭。"
